github: alexstewartja
custom: ["https://www.paypal.com/donate?business=iamalexstewart%40gmail.com&no_recurring=0&item_name=Laravel+Attribute+Observer&currency_code=USD", "https://www.buymeacoffee.com/asja"]
